### ISSUE TITLE
The variables have different time points?

### ISSUE THREAD

**Issue by chooron** [mlech26l/learning-long-term-irregular-ts#5]
I run your ode-lstms in the code. However, I found the dataset are sharing the same time points. Now, I am facing a dataset which have differents time points, and the input of the time are not 1-dim. How can I apply the model for the different time points?

**Comment by mlech26l** [comment]
The code should also work for datasets where a batch contains sequences with different elapsed time tensors

**Comment by chooron** [comment]
> 

Thank you for your reply to my comments，In my dataset, the shape of the input is [batch_size, seq_len, feature dim], according to your explanation, the shape of my time points can be [batch_size, seq_len, feature dim], which corresponding to the input ?

**Comment by mlech26l** [comment]
The time input should be of the shape [batch_size,seq_len,1] and the input features [batch_size, seq_len, feature dim], i.e., one feature vector has a single time point associated with it.

Having both, the time input and the feature input of shape [batch_size, seq_len, feature dim], i.e., each feature has a different time, is not supported by the ode-lstms

**Comment by chooron** [comment]
ohh! Thank you for you reply, my dataset need the shape of the time input which is [batch_size, seq_len, feature dim], but your work of the ode-lstms still give me great help! 
I will continue to look for other models that can be applied to my dataset，and I hope you have a nice day!

**Comment by mlech26l** [comment]
Thanks. Have a nice day too!
