### ISSUE TITLE
Cannot download the mujoco Walker2D dataset

### ISSUE THREAD

**Issue by wutianyuan1** [mlech26l/learning-long-term-irregular-ts#6]
I tried to reproduce the mujoco walker2D experiment reported in the paper, however it seems the dataset url is invalid now. Here is the output of `wget`:
```
Connecting to pub.ista.ac.at (pub.ista.ac.at)|81.223.84.195|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-27 16:29:36 ERROR 404: Not Found.
```

**Comment by mlech26l** [comment]
@wutianyuan1 Thanks for letting me know.

I have updated the URL to ```https://www.mit.edu/~mlechner/walker.zip```
